#!/usr/bin/env bash

tagpfx="v"
last_tag="$(git tag -l "${tagpfx}*" | sort | tail -1)"
iter=1
ok=
while [[ -z "${ok}" ]]; do
    this_tag="$(date +"${tagpfx}%Y-%m-%d-$(printf "%02d" "${iter}")")"
    iter="$(( iter + 1))"

    case "$( (echo "${this_tag}"; echo "${last_tag}") | sort | tail -1 )" in
        "${last_tag}")
            ;;
        "${this_tag}")
            ok=yes
            ;;
    esac
done

git tag "${this_tag}"
git push --atomic origin main "${this_tag}"
